name: Download Godot source code


description: Download and extract the Godot source code for use in compiling


inputs:
  version:
    description: Version of Godot source code to download
    default: "fix_multiplayer_sync"

#https://github.com/BlackShift/godot/archive/refs/heads/fix_multiplayer_sync.zip
runs:
  using: "composite"

  steps:
    - name: Download and extract Godot
      shell: bash
      run: |
        curl -fLO https://github.com/BlackShift/godot/archive/refs/heads/${{ inputs.version }}.tar.gz
        tar -xvzf ${{ inputs.version }}.tar.gz --strip-components 1 --exclude=".github"